use crate::*;

/// Events generated from user inputs.
#[allow(missing_docs)]
#[derive(Serialize, Deserialize, PartialEq, Eq, Hash, Copy, Clone, Debug)]
pub enum InputEvent {
    Quit,
    MenuNorth,
    MenuWest,
    MenuEast,
    MenuSouth,
    MenuSelect,
    MenuCancel,
    SpeedToggle,
    ZoomToggle,
    Teleport(u8),
}

/// Events generated by the game's runtime.
#[derive(PartialEq, Copy, Clone, Debug)]
pub enum GameEvent {
    /// A team won the game.
    GameWon(Team),
    /// Damage the specified entity by this amount.
    DamageEntity(Entity, f64),
    /// Kill the specified entity.
    KillEntity(Entity),
    /// A leader died.
    LeaderDied(u8),
    /// Spawn a creep at the specified position in the specified team.
    SpawnCreep(Point, Team),
    /// Spawns a leader using the `TeamLeaders`' index and a position.
    SpawnLeader(Point, u8),
}
