use crate::*;

/// Events generated from user inputs.
#[allow(missing_docs)]
#[derive(Serialize, Deserialize, PartialEq, Eq, Hash, Copy, Clone, Debug)]
pub enum InputEvent {
    Quit,
    MenuNorth,
    MenuWest,
    MenuEast,
    MenuSouth,
    MenuSelect,
    MenuCancel,
    SpeedToggle,
    ZoomToggle,
    Teleport(u8),
}

/// Units available to spawn
#[derive(PartialEq, Copy, Clone, Debug)]
pub enum Unit {
    /// A normal creep
    Creep,
    /// A creep in form of a small tree
    Treant,
    /// A bear with good resistance
    Bear,
}


/// Events generated by the game's runtime.
#[derive(PartialEq, Copy, Clone, Debug)]
pub enum GameEvent {
    /// A team won the game.
    GameWon(Team),
    /// Damage the specified entity by this amount.
    DamageEntity(Entity, f64),
    /// Kill the specified entity.
    KillEntity(Entity),
    /// A leader died.
    LeaderDied(u8),
    /// Spawn a unit at the specified position in the specified team.
    SpawnUnit(Point, Team, Unit),
    /// Spawns a leader using the `TeamLeaders`' index and a position.
    SpawnLeader(Point, u8),
}
